--- PV as STATIC provisioning

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol1
spec:
  accessMode:
  - ReadWriteOnce
  capacity:
    storage: 500Mi
  gcePersistentDisk:
    pdName: pd-disk
    fsType: ext4

--- INSTEAD USE StorageClass as DYNAMIC provisioning

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: google-storage
provisioner: kubernetes.io/gce-pd

--- AND

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  storageClassName: google-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
