apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
spec:
  containers:
  - name: myfrontend
    image: nginx
    volumeMounts:
    - mountPath: "/var/www/html"
      name: mypd
  volumes:
  - name: mypd
    hostPath:
      path: /data
      type: DirectoryOrCreate
