# kubectl create clusterrole cluster-admin --resource=nodes --verb=create,list,get,delete --dry-run=client -o yaml
#
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: cluster-admin
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - create
  - list
  - get
  - delete
